### ISSUE TITLE
hertz price function fails

### ISSUE THREAD

**Issue by grctest** [BTS-CM/Bitshares-HUG-REST-API#1]
After adding the private price feed publishers manually (instead of using witness/committee fed price feed publishers) the users who aren't currently publishing price feeds display with 0 in all fields.

```
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
{'base': {'amount': 91670000, 'asset_id': '1.3.1382'}, 'quote': {'amount': 2648000000, 'asset_id': '1.3.0'}}
{'base': {'amount': 346493, 'asset_id': '1.3.1382'}, 'quote': {'amount': 10000000, 'asset_id': '1.3.0'}}
{'base': {'amount': 329261, 'asset_id': '1.3.1382'}, 'quote': {'amount': 10000000, 'asset_id': '1.3.0'}}
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
{'base': {'amount': 1, 'asset_id': '1.3.1382'}, 'quote': {'amount': 36, 'asset_id': '1.3.0'}}
{'base': {'amount': 0, 'asset_id': '1.3.0'}, 'quote': {'amount': 0, 'asset_id': '1.3.0'}}
```

Solution: Check if the amount is greater than 0, if not skip!

---

Initial warning: Internal Server Error

Second debug message via `tail -n 50 gunicorn_error_log' in the HUG server terminal:
```
[2018-01-16 21:21:37 +0000] [4087] [ERROR] Error handling request /get_hertz_value?api_key=123abc
Traceback (most recent call last):
  File "/home/btsapi/HUG/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/api.py", line 421, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/falcon/api.py", line 242, in __call__
    responder(req, resp, **params)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 692, in __call__
    self.render_content(self.call_function(input_parameters), request, response, **kwargs)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 633, in call_function
    return self.interface(**parameters)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/btsapi/hug_script.py", line 163, in get_hertz_value
    settlement_price['api_calculated_rate'] = (int(settlement_price['quote']['amount'])/settlement_price['base']['amount'])/10
ZeroDivisionError: division by zero

```

**Comment by grctest** [comment]
https://github.com/BTS-CM/Bitshares-HUG-REST-API/commit/b05bd51b05ad13da513542026d6be66dcc31c9ae

Fixed!
