### ISSUE TITLE
Hertz value page errors

### ISSUE THREAD

**Issue by grctest** [BTS-CM/Bitshares-HUG-REST-API#2]
```[2018-03-07 06:53:34 +0000] [10847] [CRITICAL] WORKER TIMEOUT (pid:10874)
[2018-03-07 06:53:35 +0000] [8685] [INFO] Booting worker with pid: 8685
[2018-03-07 12:18:56 +0000] [11684] [ERROR] Error handling request /home
Traceback (most recent call last):
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 42, in rpcexec
    return super(BitSharesNodeRPC, self).rpcexec(payload)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 160, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: Assert Exception: _index[space_id].size() > type_id:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/btsapi/HUG/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/api.py", line 421, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/falcon/api.py", line 242, in __call__
    responder(req, resp, **params)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 692, in __call__
    self.render_content(self.call_function(input_parameters), request, response, **kwargs)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 633, in call_function
    return self.interface(**parameters)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/hug/interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/btsapi/hug_script.py", line 103, in root
    hertz_json = get_hertz_value('123abc')
  File "/home/btsapi/hug_script.py", line 179, in get_hertz_value
    price = market.ticker()["quoteSettlement_price"] # Get Settlement price of USD
  File "/home/btsapi/python-bitshares/bitshares/market.py", line 154, in ticker
    self["quote"]["id"],
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 195, in method
    r = self.rpcexec(query)
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 50, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _index[space_id].size() > type_id:
```

**Comment by grctest** [comment]
https://btsapi.grcnode.co.uk/get_hertz_value?api_key=123abc works properly.

Perhaps this is the offending line?
`price = market.ticker()["quoteSettlement_price"] # Get Settlement price of USD`

**Comment by grctest** [comment]
```
{'core_exchange_rate': 4.300673077 BTS/USD, 'quoteSettlement_price': 5.283240569 BTS/USD, 'baseVolume': 11,043,733.19137 BTS, 'quoteVolume': 1,967,656.3689 USD, 'lowestAsk': 5.866794450 BTS/USD, 'highestBid': 5.833214989 BTS/USD, 'latest': 5.860428404 BTS/USD, 'percentChange': 15.21}
---
core_exchange_rate
quoteSettlement_price
baseVolume
quoteVolume
lowestAsk
highestBid
latest
percentChange
===
5.283240569 BTS/USD
```

Hmm.. perhaps the connected full node does not have the required extensions for providing market ticker info?

**Comment by grctest** [comment]
Interesting.. 

```
Server: wss://bitshares.dacplay.org/ws
Traceback (most recent call last):
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 42, in rpcexec
    return super(BitSharesNodeRPC, self).rpcexec(payload)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 160, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: Assert Exception: _index[space_id].size() > type_id:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 44, in <module>
    print(market.ticker())
  File "/home/btsapi/python-bitshares/bitshares/market.py", line 154, in ticker
    self["quote"]["id"],
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 195, in method
    r = self.rpcexec(query)
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 50, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _index[space_id].size() > type_id:
```

Not the same as an unavailable server:
```
Lost connection to node during wsconnect(): wss://bitshares.crypto.fans/ws (2/-1
```

**Comment by grctest** [comment]
Removing wss://bitshares.dacplay.org/ws from the server list solved this glitch.

Perhaps try/except handling would make the script more redundant against failing servers?
