### ISSUE TITLE
[HUG] New user + Stats page -> Error?

### ISSUE THREAD

**Issue by grctest** [BTS-CM/Bitshares-HUG-REST-API#6]
User asked for stats (google tester? It's not available as an implicit intent..)

'Non matching existing property - registered & returned' message

Error message:
```
Error: Unexpected error!
    at catch_error (/user_code/index.js:55:21)
    at hug_request.then.body (/user_code/index.js:1713:14)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

function: get_user_ranking
failed check: success & valid_key (true checks)
hug logs: all returned 'success 200' (though a 'success=fail' returns 200 too)

A firebase log stating 'account created' after the error occurred may imply that it's an async problem - we tried to get the stats before the account had finished being registered.

**Comment by grctest** [comment]
```gg_id: parse_userId(conv)```

The use of the above in HUG parameters may not be fast enough to register the gg_id before executing the HUG request.

Either:
1. We promise parse_userid exists before submitting hug requests
2. Upon matching no gg_id in python, attempt to register gg_id then recursively call function?
    Might be too slow? (<5 secs)

**Comment by grctest** [comment]
Wrong repo
